services:
  
  # nginx service
  web:
    image: nginx:latest # Image to use
    container_name: web # Container name
    volumes: 
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf # Mounting volumes
    # restart: unless-stopped # Restart policy
    # tty: true # Interactive terminal for the container to run in the background and forward ports to host
    ports:
      # Host port to container port mapping (8001:80) 
      # 8001 port on host is mapped to 80 port on container
      - "8001:80" 
    # volumes: # Mounting volumes
    #   - ./:/var/www
    #   - ./docker-compose.yaml:/var/www/docker-compose.yaml  
  # php
  app:
    build: 
      # context: .
      dockerfile: ./php/Dockerfile
    container_name: app
    volumes:
      - ./app:/app
  # mysql
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql_docker_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  # redis

volumes:
  mysqldata: